includes:
  - ../base.yaml
  - ../../GOODTwitter.yaml
ood_param:
  - 1
extra_param:
  -     # LA
    - 1
    - 0.1
    - 0.01
#    - 0
  -      # EC
    - 0
  -      # EA
    - 0.1
    - 0.01
    - 0.001
#    - 0
  -       # r decay interval
    - 30
  -       # EF
#    - 0
    - 0.1
    - 0.01
    - 0.001
  -
    - true
pre_train:
  - 5