includes:
  - ../base.yaml
  - ../../FPIIFMotif.yaml
ood_param:   # information constraint
  - 0
#  - 1
extra_param:
  -     # LA
    - 20
    - 10
    - 3
    - 1
    - 0.3
    - 0.1
#    - 3e-2
#    - 1e-2
#    - 3e-3
#    - 1e-3
#    - 0
  -      # EC
    - 0
  -      # EA
    - 20
    - 10
    - 3
    - 1
    - 0.3
    - 0.1
#    - 3e-2
#    - 1e-2
#    - 3e-3
#    - 1e-3
  -       # r decay interval
    - 50
  -       # EF
    - 0
  -           # If batchnorm/instancenorm (true/false)
    - true
pre_train:
  - 100
