includes:
  - ../base.yaml
  - ../../LBAPcore.yaml
ood_param:   # information constraint
  - 1
extra_param:
  -     # LA
    - 1
    - 0.1
    - 0.01
  -      # EC
    - 0
  -      # EA
    - 0.1
    - 0.01
    - 0.001
  -       # r decay interval
    - 90
  -       # EF
    - 0.1
    - 0.01
  -           # If batchnorm/instancenorm (true/false)
    - true
pre_train:
  - 20