includes:
  - ../base.yaml
ood_param:   # information constraint
  - 0
  - 1
extra_param:
  -     # LA
    - 100
#    - 20
    - 10
#    - 5
    - 1
    - 0.1
    - 0
  -      # EC
    - 0
  -      # EA
    - 100
#    - 20
    - 10
#    - 5
    - 1
    - 0.1
    - 0
  -       # r decay interval
    - 40
  -       # EF
    - 0
  -           # If batchnorm/instancenorm (true/false)
    - true