includes:
  - base.yaml
model:
  model_name: CIGAvGIN
ood:
  ood_alg: CIGA
  ood_param: 0.6
  extra_param:
    - 1
    - 0.5
train:
  max_epoch: 200
  lr: 0.0001
  weight_decay: 0.0001
  pre_train: 5
log_file: exp_0
clean_save: true
