includes:
  - base.yaml
model:
  model_name: DIRvGIN
ood:
  ood_alg: DIR
  ood_param: 0.8
  extra_param:
    - 0.1
train:
  max_epoch: 200
  train_bs: 32
  lr: 0.0001
  weight_decay: 0.0001
log_file: exp_0
clean_save: true
