includes:
  - base.yaml
model:
  model_name: DIRGIN
ood:
  ood_alg: DIR
  ood_param: 0.8
  extra_param:
    - 10.0
train:
  max_epoch: 100
  lr: 0.001
  mile_stones:
    - 150
  weight_decay: 0.0
log_file: exp_0
clean_save: true
