includes:
  - base.yaml
model:
  model_name: GSATvGIN
ood:
  ood_alg: GSAT
  ood_param: 1.0
  extra_param:
    - true
    - 10
    - 0.7
train:
  max_epoch: 200
  lr: 0.0001
  weight_decay: 0.0001
  pre_train: 5
log_file: exp_0
clean_save: true
