includes:
  - base.yaml
model:
  model_name: DIRGIN
ood:
  ood_alg: DIR
  ood_param: 0.25    # causal ratio
  extra_param:
    - 1e-2     # additional loss control
train:
  max_epoch: 200
  lr: 1e-3
  mile_stones: [150]


