includes:
  - ../base.yaml
  - ../../GOODSST2.yaml
ood_param:
  - 0
  - 1
extra_param:
  -     # LA
    - 1
    - 0.1
    - 0.01
#    - 0
  -      # EC
    - 0
  -      # EA
    - 0.1
    - 0.01
#    - 0
  -       # r decay interval
    - 60
  -       # EF
#    - 0
    - 0.1
    - 0.01
  -
    - true
pre_train:
  - 50