includes:
  - ../base.yaml
extra_param:
  -     # LA
    - 0.1
    - 1e-2
  -      # EC
    - 0
  -      # EA
    - 0.1
    - 1e-2
  -       # r decay interval
    - 50
  -       # EF
    - 0
  -           # If batchnorm/instancenorm (true/false)
    - true
#    - false
