includes:
  - base.yaml
model:
  model_name: DIRvGIN
ood:
  ood_alg: DIR
  ood_param: 0.6
  extra_param:
    - 0.01
train:
  max_epoch: 100
  lr: 0.001
  mile_stones:
    - 300
  weight_decay: 0.0
log_file: exp_0
clean_save: true
