includes:
  - ../base.yaml
  - ../../GOODHIV.yaml
ood_param:
  - 1
extra_param:
  -     # LA
    - 1
    - 0.1
    - 0.01
  -      # EC
    - 0
  -      # EA
    - 0.1
    - 0.01
#    - 0.001
  -       # r decay interval
    - 60
  -       # EF
    - 0
    - 0.1
    - 0.01
#    - 0.001
  -
    - true
#    - false
pre_train:
  - 50